name: Python

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Python setup
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
        cache: pip
    - name: install dependencies
      run: pip install -e .[test]
    - run: pytest


    # build and publish
    - name: build package
      if: startsWith(github.ref, 'refs/tags/')  # tags pushed
      run: |
        pip install build
        python -m build  # build wheel and source tarball
    - name: publish
      if: startsWith(github.ref, 'refs/tags/')  # tags pushed
      uses: pypa/gh-action-pypi-publish@release/v1
      env:
        url: https://pypi.org/p/selfish


permissions:
  id-token: write
  contents: read
